### ISSUE TITLE
Specify interface for multi-T

### ISSUE THREAD

**Issue by j0sh** [livepeer/go-livepeer#773] opened 2019-03-06 06:23 UTC

**Comment by angyangie** [comment] 2019-03-13 21:17
Good summary from Discord on current discussion:

**Angie:** 

 I found it really useful to summarize how transcoding is being done currently. This is useful to me, and perhaps can be included in our release proposal for anyone else, esp new team members, as a refresher on how that works: https://hackmd.io/ScAcIALaSVuczUYVqvvkrw. 

That said, in thinking about what this interface can potentially look like, keeping in mind a round robin approach, I have some questions I was hoping you could help me answer:

1. My thinking is that, instead of  waiting for ServeSegment to finish transcoding, and for the transcoding result to be available, a certain # of segments can be sent sequentially. So, if there are 3 Ts available,  we should know that three segments can be "in process" at a time. I'm not sure how or where we'd accomplish that. Could you point me in the right direction here?

2. Say we have #1 done, the next step would just be to turn n.Transcoder into a list instead of a single value. Every time a T connects to the O, they'd be added to the list. We could then use our pseudo-code algorithm to pop one from the list, use it, and push it back on the list once transcoding is done. Since we already have n.SegmentChans[md.ManifestID], we can push transcoded results there. Does that make sense?

3. However, out of order segments become a problem. So, we'd need to check Seq number in order to put the results back together in the correct order. If we're not retrying, at least initially, we could still grab the Seq number of the failed segment, and count it as "done", and move on to return the next transcoded segment in the sequence. Where in the code does "putting segments back together into a stream" happen?

**Josh:**

> So, if there are 3 Ts available,  we should know that three segments can be "in process" at a time. I'm not sure how or where we'd accomplish that.

I don't think this should be the goal for multi-T here.

* Os can already serve segments from  as many different jobs up to their capacity cap -maxSessions

* For each job, only one segment can be transcoded at a time. This is a valuable feedback mechanism that is telling us segments are not being transcoded in real time. Note there is a bit of a buffer here; only the transcode loop itself is queued; downloads + uploads can be done concurrently.

* We can change the length of the queue to allow more in-flight segments beyond the current cap of 1 segment queued

* That being said, I'm not sure we should be changing the length of queue at all; it's not really the focus here. The focus is on scalability of O itself; that is, enabling O to process more segments via attached Ts than it would otherwise be able to do locally.

* In effect, we want to provide a path for increasing the -maxSessions cap, not  in allowing multiple in-flight segments for each job

* I know there's recent concern about OrchestratorBusy but in my eyes this is the feedback mechanism working exactly as intended. It's telling us something is wrong here and we can't process this in real time. We don't want to obscure this by increasing the length of the transcode queue.

> next step would just be to turn n.Transcoder into a list instead of a single value

Perhaps. Another approach might be to make n.Transcoder into the "entry point" for the API, where we  handle all the coordination within that function.

One thing that's been helpful for me is to think of features in terms of abstractions, and how that new feature fits into the existing high-level program flow. This is why defining the interface/API (the abstraction) is an explicit step here, rather than looking at the nitty gritty details of the implementation (at least, not quite yet). So what you're doing with trying to understand the flow of the transcode loop is very valuable and the right step. I'd continue to evaluate this in terms of the high-level flow and how the API/interface would fit into the current flow. We have an algorithm; now let's look at the abstraction for exposing that algorithm to the program.

> However, out of order segments become a problem. 

Orchestrators themselves should be fairly agnostic to segment numbering (do we still send segment numbers? we actually don't really need to anymore). But you are correct that out of order segment numbers would be an issue if we were to do multiple in-flight segments per job, and triggering that would be a big honking signal that something is wrong. In fact, the easiest way to address this problem is by preventing it from happening in the first place: we don't allow multiple in-flight segments. The second easiest way to handle this would be to reorder segments on the broadcaster upon playlist insertion (which we might have to do anyway).

**Angie:**

> I don't think this should be the goal for multi-T here.

Thanks for helping me focus here. I see that reducing latency isn't the goal - it's to get to 99% success rate. Having multiple segments in-flight would not necessarily get us there. In fact, it might do the opposite, if it makes it difficult for us to check whether segments are being transcoded in real time. Good to realize processing one segment at a time is very much intentional.

> downloads + uploads can be done concurrently.... In effect, we want to provide a path for increasing the -maxSessions cap, not  in allowing multiple in-flight segments for each job

Good to know!

> Perhaps. Another approach might be to make n.Transcoder into the "entry point" for the API, where we  handle all the coordination within that function....

Yes, I realize I'm trying to figure out the nitty gritty details. So, is what you're saying, that n.Transcoder could be the entry-point to our algorithm, which could just live in a different function? I'll think about that some more.

> ... preventing it from happening in the first place: we don't allow multiple in-flight segments. The second easiest way to handle this would be to reorder segments on the broadcaster upon playlist insertion (which we might have to do anyway).

That makes sense. Seems like  this is something that we punt to the end as well, and handle on the broadcaster itself if needed.  But for now, focus on the algorithm and interface aspect of things

**Comment by angyangie** [comment] 2019-03-13 22:17
Preliminary interface (WIP):

```golang
type Transcoder interface {
    SelectTranscoder()
    Transcode(fname string, profiles []ffmpeg.VideoProfile) ([][]byte, error)
    PushTranscoderToList()
}

var localTranscoderList *LocalTranscoderList

type LocalTranscoderList struct {
    transcoder []*LocalTranscoder
}

type LocalTranscoder struct {
    workDir    string
    capacity   int
}

func NewLocalTranscoder(workDir string, cap int) Transcoder {
	localTrans := LocalTranscoder{workDir: workDir, capacity: cap}
         localTranscoderList = append(localTranscoderList.transcoder,  localTrans)
         return &localTranscoderList
}
```

`LocalTranscoderList` would implement the Transcoder interface in this example. Same on the remote side:

```golang
type RemoteTranscoderList struct {
    transcoder []*RemoteTranscoder
}

type RemoteTranscoder struct {
    node   *LivepeerNode
    stream net.Transcoder_RegisterTranscoderServer
    eof    chan struct{}
}

var remoteTranscoderList *RemoteTranscoderList

func NewRemoteTranscoder(n *LivepeerNode, stream net.Transcoder_RegisterTranscoderServer, cap int) *RemoteTranscoder {
	remoteTrans := RemoteTranscoder{
		node:     n,
		stream:   stream,
		eof:      make(chan struct{}, 1),
		capacity: cap,
	}
	remoteTranscoderList = append(remoteTranscoderList.transcoder,  remoteTrans)
	return &remoteTranscoderList

}
```

`SelectTranscoder()` would grab a transcoder from the list, and send it a transcoded segment. While that transcoder were doing work, and that segment was still in flight, the transcoder wouldn't be a part of the list. If there is an `ErrOrchBusy`, we don't place the T back on the list. Once we have a successful transcoded segment, we call `PushTranscoderToList` and place that T at the end of the list.

`PushTranscoderToList` and `SelectTranscoder` would be called within `Transcode(fname string, profiles []ffmpeg.VideoProfile) ([][]byte, error)`. `SelectTranscoder()` would grab a transcoder from the list, and send it a transcoded segment. While that transcoder were doing work, and that segment was still in flight, the transcoder wouldn't be a part of the list. If there is an `ErrOrchBusy`, we don't place the T back on the list. Once we have a successful transcoded segment, we call `PushTranscoderToList` and place that T at the end of the list.

**Comment by angyangie** [comment] 2019-03-14 18:06
This iteration of the interface includes capacity management, and registering/unregistering T's. 

**Important notes:**

Registration: If T has a capacity of 5, we'd be adding 5 copies of that T to the list. If we're popping T's from the list in transcoder, we'd be sending the next consecutive segments to the same transcoder. Since we're not dealing with an `ErrOrchBusy` error on the T side, this is okay. The goal for multi-T is not to address `ErrOrchBusy`. That would be multi-O. Transcoder should be able to handle up to its capacity in concurrent encoding. From Josh: this doesn't change the O's logic of only allowing one concurrent segment per job, but in this case different jobs would use the same T up to T's capacity before switching to the next one.

Local/Remote transcoders: We already have a fairly clean separation between local / remote transcoding so not a lot needs to be a ton of work there specifically. To be clear, a "standalone transcoder" is running remotely (ot_rpc being O/T related RPC calls). A "local transcoder" usually references the O itself doing the transcoding, rather than on a standalone T process. 

Number of segments in-flight: It is NOT our goal to change the number of segments in flight at once per stream. For example, we are not handling the following situation: instead of waiting for ServeSegment to finish transcoding, and for the transcoding result to be available, we could send a certain # of segments sequentially. So, in that example, if there were 3 Ts available, we'd have to track these three segments "in process" at once. 

From @j0sh : 
- For each job, only one segment can be transcoded at a time. This is a valuable feedback mechanism that is telling us segments are not being transcoded in real time. Note there is a bit of a buffer here; only the transcode loop itself is queued; downloads + uploads can be done concurrently.
- We can change the length of the queue to allow more in-flight segments beyond the current cap of 1 segment queued
- That being said, I'm not sure we should be changing the length of queue at all; it's not really the focus here. The focus is on scalability of O itself; that is, enabling O to process more segments via attached Ts than it would otherwise be able to do locally.
- In effect, we want to provide a path for increasing the -maxSessions cap, not  in allowing multiple in-flight segments for each job
- I know there's recent concern about OrchestratorBusy but in my eyes this is the feedback mechanism working exactly as intended. It's telling us something is wrong here and we can't process this in real time. We don't want to obscure this by increasing the length of the transcode queue.
- Out of order segments: Orchestrators themselves should be fairly agnostic to segment numbering (do we still send segment numbers? we actually don't really need to anymore). But out of order segment numbers would be an issue if we were to do multiple in-flight segments per job, and triggering that would be a big honking signal that something is wrong. In fact, the easiest way to address this problem is by preventing it from happening in the first place: we don't allow multiple in-flight segments. The second easiest way to handle this would be to reorder segments on the broadcaster upon playlist insertion (which we might have to do anyway).

**Updated Interface:**

```golang
type Transcoder interface {
    Transcode(fname string, profiles []ffmpeg.VideoProfile) ([][]byte, error)
}

func registerTranscoder(transcoder, list, capacity) {
   for i = 0; i < capacity; i++ {
        list = push(list, transcoder)
   }
}

func unregister(transcoder, list) {
   list = filter(list, fun(c){ c == transcoder })
}

// LOCAL TRANSCODER CODE BELOW

type LocalTranscoderList struct {
   transcoders  []*LocalTranscoder
}

type LocalTranscoder struct {
    workDir         string
}

var localTranscoderList *LocalTranscoderList

func NewLocalTranscoder(workDir string, cap int) Transcoder {
    localTransc = &LocalTranscoder{workDir: workDir}
    registerTranscoder(localTransc, localTranscoderList, cap)
}

func (lt *LocalTranscoderList) Transcode(fname string, profiles []ffmpeg.VideoProfile) ([][]byte, error) {
     res, err := { transcode segment here }
     if err != nil {
        return nil, err
     }
     return res, nil
}

// REMOTE TRANSCODER CODE BELOW

type RemoteTranscoderList struct {
    transcoders  []*RemoteTranscoder
}

type RemoteTranscoder struct {
    node          *LivepeerNode
    stream        net.Transcoder_RegisterTranscoderServer
    eof           chan struct{}
}

var remoteTranscoderList *RemoteTranscoderList

func NewRemoteTranscoder(n *LivepeerNode, stream net.Transcoder_RegisterTranscoderServer, cap int) {
	remoteTrans := RemoteTranscoder{
		node:          n,
		stream:      stream,
		eof:            make(chan struct{}, 1),
	}
	registerTranscoder(remoteTrans, remoteTranscoderList, cap)
}

func (rt *RemoteTranscoderList) Transcode(fname string, profiles []ffmpeg.VideoProfile) ([][]byte, error) {
    t = pop(remoteTranscoderList)
    res, err := { transcode segment here with t}
     if err != nil {
             unregister(t, remoteTranscoderList)
             return nil, err
     }
     rt.transcoders = push(t, remoteTranscoderList)
     return res, nil
}
```

**Questions left to answer, which could be tackled upon implementation:**
- How do we deal with errors from localTranscoders?
- Is LocalTranscoderList the best way to deal with local capacity?
- We'll need to handle reordering segments on the broadcaster

**Comment by angyangie** [comment] 2019-03-14 22:36
Seems like this might be the winner .... https://play.golang.org/p/6dPQOrDhBbz

```golang
package main

import (
	"fmt"
)

type T interface {
	Transcode()
}

type RT struct {
	capacity int
}

func NewRemoteTranscoder(capacity int) *RT {
  return &RT{ capacity: capacity }
}

func (r *RT) Transcode() {
}

func (r *RT) Capacity() int {
	return r.capacity
}

type RT_Manager struct {
	remotes []*RT
}

func (m *RT_Manager) Register(t *RT) {
	for i := 0; i < t.Capacity(); i++ {
		m.remotes = append(m.remotes, t)
	}
}

func (m *RT_Manager) Unregister(t *RT) {
	var remotes []*RT
	for _, v := range m.remotes {
		if v == t {
			continue
		}
		remotes = append(remotes, v)
	}
	m.remotes = remotes
}

func (m *RT_Manager) Transcode() {
	t, remotes := m.remotes[0], m.remotes[1:]
	m.remotes = remotes
	t.Transcode()
	m.remotes = append(m.remotes, t)
}

type Node struct {
	manager    *RT_Manager
	transcoder T
}

type LocalTranscoder struct {
	//... same as what we have now ...
}

func (t *LocalTranscoder) Transcode() {
}

func NewLocalTranscoder() *LocalTranscoder {
	return &LocalTranscoder{}
}

func (n *Node) ServeTranscoder(capacity int) {
	if n.manager == nil {
		return
	}
	t := NewRemoteTranscoder(capacity)
	n.manager.Register(t)
	defer n.manager.Unregister(t)
	// ... do rest ...
}

func main() {
	//for remotes - populate manager
	manager := &RT_Manager{}
	remote := Node{manager: manager, transcoder: manager}

	// for local - leave manager empty
	local := Node{transcoder: NewLocalTranscoder()}

	fmt.Printf("Hello %v %v", remote, local)
}
```

This interface has a clear structure for transcoder management (for remote transcoders) and a separation between the actual transcoder. Technically we could just "register" a local transcoder too under the same interface up to the local capacity. However, it's not needed (only one local transcoder can exist at a time) and makes the separation between transcoder and manager murkier. We'd also run the risk of covariance issues if we ever wanted to extend registration to other types of transcoders, since we're forcing registrations to share a common T interface.

**Comment by angyangie** [comment] 2019-04-16 14:17
This is done. Closing

**Closed as completed by angyangie** 2019-04-16 14:17 UTC
