### ISSUE TITLE
Context deadline exceeded during transcoder txns with Parity

### ISSUE THREAD

**Issue by dob** [livepeer/go-livepeer#448] opened 2018-05-25 18:42 UTC
**Describe the bug**
This is reported by Discord user pfun. He is running a local Parity node, and trying to execute the "Become a transcoder flow". Sometimes the approve txn gives `context deadline exceeded` and even though it confirms on Etherscan, the node never submits the bond txn. Somtimes it gets through approve, and bond. But it has never made it through approve, bond, and transcoder in one shot.

**To Reproduce**

1. Sync a Parity light node with `parity --cache-size=64000 --min-peers=50 --max-peers=200 --light`
2. Similar issue with a geth node with `geth --cache 256 --maxpeers 50 --syncmode light --rpc --rpcapi db,eth,net,web3 --ws --wsorigins "*"`
3. Start a Livepeer node pointing at the local parity node. Tried both IPC and WS. 
4. Get some ETH and LPT and attempt to "Become a Transcoder"
5. See that the node can't make it through all txns. Here is some provided log output as an example.

```
^H1I0525 14:21:44.924366    6511 webserver.go:263] Bonding 1...
I0525 14:21:45.620158    6511 base.go:207]
****************************Eth Transaction****************************

Invoking transaction: "approve".  Hash: "0x11144e22a0558d267a6c02291a95eec312c9dd8e7dc361ba8384cef2fdd8a0ed".  Params: [[81 27 196 85 109 130 58 233 150 48 174 141 226 139 155 128 223 144 234 46] 1]

***********************************************************************
I0525 14:24:49.698821    6511 base.go:207]
****************************Eth Transaction****************************

Invoking transaction: "bond".  Hash: "0x97ff3b8b529d49cc01c62d38186f1599f5c1ea7fcd0996fee694101b2a90e6e5".  Params: [1 [157 43 78 92 75 31 216 29 6 184 131 176 172 166 97 183 113 195 158 163]]

***********************************************************************
I0525 14:26:09.701203    6511 webserver.go:279] Registering transcoder 0x9D2B4E5c4b1fd81D06b883B0Aca661B771c39EA3
I0525 14:26:10.524461    6511 base.go:207]
****************************Eth Transaction****************************

Invoking transaction: "transcoder".  Hash: "0x5dac908825cabc49c97b8593c60f63eb2d579c16a024c51c458938b13e68f56d".
  Params: [450000 150000 145]

***********************************************************************
E0525 14:36:10.524692    6511 webserver.go:289] context deadline exceeded
```

**Expected behavior**
The three txns to succeed.

**Additional context**
aws t2.medium, ubuntu 16.04 lts

Livepeer Node Version: 0.2.3-unstable
Parity/v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0

**Comment by dob** [comment] 2018-05-25 18:54
Seeing a lot of `E0525 18:50:20.245058    7819 eventmonitor.go:275] Error with header subscription for BlockWatcher: missing required field 'mixHash' for Header` in the Livepeer log. 

Googling for this shows that it was potentially because of an incompatibility in the JSON api's of parity and geth, but that it was supposedly fixed in 2016.

**Comment by rfunduk** [comment] 2018-05-25 18:57
Thanks for your help @dob!

I wanted to just clarify that the context deadline exceeded stuff is what happens with geth light (with peers, but very few and acting strangely, very little in log).

So geth was nothing but trouble all around, but parity really _looks_ like it should be working (lots of peers, definitely stays in sync at all times, etc) but this is what happens:

```
******************************Eth Transaction******************************

Invoking transaction: "approve".  Hash: "0x6413d37f9f7d7825da613b3c324fe259029ffcdda9b2e8e4714660afcfbce675".  Params: [[81 27 196 85 109 130 58 233 150 48 174 141 226 139 155 128 223 144 234 46] 10000]

***************************************************************************
E0525 18:09:57.191126    7819 eventmonitor.go:275] Error with header subscription for BlockWatcher: missing required field 'mixHash' for Header
E0525 18:09:57.191488    7819 webserver.go:267] tx 0x6413d37f9f7d7825da613b3c324fe259029ffcdda9b2e8e4714660afcfbce675 failed
```

Notice how https://etherscan.io/tx/0x6413d37f9f7d7825da613b3c324fe259029ffcdda9b2e8e4714660afcfbce675 succeeded just fine, but evidently parity/livepeer did not see that.

When @dob suggested that since I had previously gotten through approve/bond, I should just say to bond 0 to skip approve/bond:

```
I0525 18:29:52.551068    7819 webserver.go:279] Registering transcoder 0x9D2B4E5c4b1fd81D06b883B0Aca661B771c39EA3
I0525 18:29:53.211598    7819 base.go:207]
******************************Eth Transaction******************************

Invoking transaction: "transcoder".  Hash: "0x14bf071c47a8742b1724ce6a76bd53c1de2335a3a4b52c1f23145f04cbe2a069".  Params: [450000 150000 145]

***************************************************************************
E0525 18:31:20.215301    7819 eventmonitor.go:275] Error with header subscription for BlockWatcher: missing required field 'mixHash' for Header
E0525 18:31:20.215604    7819 webserver.go:289] tx 0x14bf071c47a8742b1724ce6a76bd53c1de2335a3a4b52c1f23145f04cbe2a069 failed
```

But the transaction again did actually work and I'm now listed as a transcoder.

**Comment by yondonfu** [comment] 2018-06-21 20:07
So I think the Parity related problems are the following:

`Error with header subscription for BlockWatcher: missing required field 'mixHash' for Header`

The standard JSON-RPC spec does not include the `mixHash` field for the `eth_getBlockByNumber` RPC method. Geth includes the `mixHash` field, but Parity does not. This was supposedly fixed awhile ago, but seems to have become a problem again recently: https://github.com/paritytech/parity/issues/8841

`tx 0x14bf071c47a8742b1724ce6a76bd53c1de2335a3a4b52c1f23145f04cbe2a069 failed`

The Livepeer node said this transaction submitted using Parity failed when the transaction in fact succeeded (confirmed using Etherscan). I believe this is due to another difference between the JSON-RPC implementations for Geth and Parity. According to the [spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) for `eth_getTransactionByReceipt`, the receipt for a pending transaction should not be available. Geth follows the spec, but Parity does not - instead Parity always returns a receipt and if the transaction is still pending the `blockNumber` field would be empty. This is a problem because of the helper used by the Livepeer node to wait for confirmed transactions - the helper assumes that if a receipt is available that the transaction was mined (https://github.com/livepeer/go-livepeer/blob/master/vendor/github.com/ethereum/go-ethereum/accounts/abi/bind/util.go#L41). When using Parity, a receipt will be returned, but the status attached to the receipt will be inaccurate because the associated transaction will not have been mined yet. As a result, when the Livepeer node uses the receipt to check if a transactions succeeded or failed, it will think the transaction failed based on an inaccurate receipt status code.

This could be solved by running Parity with the `--geth` flag which will activate Geth compatibility mode. We can also change the helper used by the Livepeer node for waiting for confirmed transactions to account for returned receipts for pending transactions.

**Comment by ericxtang** [comment] 2018-06-21 21:43
Wow good job digging into this @yondonfu.  Can you update our doc so uses will know about this?

**Comment by ericxtang** [comment] 2019-04-08 20:15
Closing since we found the issue here.

**Closed as completed by ericxtang** 2019-04-08 20:15 UTC
Labels: type: bug
