### ISSUE TITLE
livepeer_cli: Default service URI when setting orch config diff than current on-chain value

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#1721] opened 2020-12-24 18:11 UTC
**Is your feature request related to a problem? Please describe.**

The default service URI when using livepeer_cli for the set orchestrator config option is always the auto-discovered URI even if the orchestrator already has a service URI stored on-chain.

**Comment by leszko** [comment] 2022-05-11 04:11
Duplicate of #2293. Closing.

**Closed as completed by leszko** 2022-05-11 04:11 UTC
Labels: bounty, tech debt
