### ISSUE TITLE
Change O config error in CLI, despite success and no errors in node logs.

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#2325] opened 2022-03-17 14:20 UTC
**Describe the bug**
When using the Livepeer CLI to change orchestrator config (option 13) I enter all the necessary details and everything goes fine but I receive the following error in the CLI: 

```
Error applying configuration:

```

When I check the node logs itself there are no errors and in fact the transactions have been sent successfully. 
The same behaviour occurs when no changes are being made. 

I believe this occurs because `/setOrchestatorConfig` returns status OK but with an empty string, which results in [`httpPostWithParams` returning an non-200 status code](https://github.com/livepeer/go-livepeer/blob/77450652be6d695a52effb87cfe94aad7f42c4ae/cmd/livepeer_cli/wizard.go#L312) and [thus the error being triggered](https://github.com/livepeer/go-livepeer/blob/77450652be6d695a52effb87cfe94aad7f42c4ae/cmd/livepeer_cli/wizard_transcoder.go#L176).

**To Reproduce**
1. Go to livepeer_cli
2. Select option 13
3. Enter details 
4. Run through the wizard and observe error

**Screenshots**
<img width="649" alt="image" src="https://user-images.githubusercontent.com/22256858/158826083-27aa2fc6-39ae-407c-b907-84d9656566d5.png">

**Comment by papabear99** [comment] 2022-03-17 15:03
I can confirm I've had this issue since July.

**Comment by leszko** [comment] 2022-05-11 03:32
I believe this one is closed by #2390. Please reopen if the error still occurs (after the next go-livepeer release).

**Closed as completed by leszko** 2022-05-11 03:32 UTC
Labels: area: cli, status: backlog, area: blockchain
