### ISSUE TITLE
HTTP500 errors when creating a new session of a stream too fast

### ISSUE THREAD

**Issue by jailuthra** [livepeer/go-livepeer#1673] opened 2020-11-30 12:02 UTC
**Describe the bug**

The Push API's handling of segments of different "external manifests" (aka sessionID, unique for a particular broadcast session of a stream) but same "internal manifest" (aka manifestID, unique per stream) is not good enough.

For example, when one stream session is over the client needs to wait for **1 minute** before opening another stream session. If they don't and their new stream session lands up at the same B node - they will get a 500 due to "Manifest already exists" error.

**To Reproduce**
1. Start a local B with `-authWebhookUrl`
2. Start an auth endpoint that always returns `{"manifestID":"SameInternalManifestID"}`
3. Do a HTTP push with a session ID, eg `curl -XPOST --data-binary @input.ts -v http://127.0.0.1:8935/live/session1/0.ts -H "accept: multipart/mixed" -i`
4. Before the `session1` is cleaned up (~1minute), do another HTTP push with a different session ID, eg `curl -XPOST --data-binary @input.ts -v http://127.0.0.1:8935/live/session2/0.ts -H "accept: multipart/mixed" -i`
5. Second push should fail with `Manifest manifestID=SameInternalManifestID already exists for streamID url=http://127.0.0.1:8935/live/session2/0.ts`

**Expected behavior**
We can consider reducing the timeout here, or better communicating the error to the client rather than throwing a generic 500.

**Additional context**
This issue was forked from this comment https://github.com/livepeer/go-livepeer/issues/1665#issuecomment-735103092

**Comment by iameli** [comment] 2020-11-30 23:46
Quick clarification from the old thread:

> Please correct me if I'm wrong, but I think 1. is less likely to happen on production compared to staging, as prod has some sharding?? Does same manifest ID always land at the same B node in prod like it does in staging?

Staging and prod are both sharded, but the implication of that is the opposite of what you say here: streams with the same `playbackid` will always be routed to the same shard, meaning the same go-livepeer broadcaster instance. When stream sessions are created, the API server copies the first four characters of the parent's `stream.playbackId` to the child's `stream.id` to ensure that this is the case. Our current prod infrastructure generally has two shards for staging and eight shards for prod, but in all cases separate sessions hit the same B.

> I think the code around manifestID is correct right now. It throws an error if two segments with different sessionIDs ("external manifests" in the PUSH /live/<>/ url) are present in proximity while having the same "internal" manifestID (which is unique for a particular stream/playbackID).

Ahh, I see the problem here. So this is another issue that came out of indexing streams by playback ID instead of by stream ID. That ended up having a lot more implications that I originally realized — it was also the root cause of our usage-tracking being broken! Maybe if I was doing this all again I wouldn't have changed the `manifestID` field to be the `stream.playbackId`, and instead advocated that we add an `aliases: []` field to the webhook that allows the stream to be served back from the `playbackId`. That's all I was going for with this change. So that might be worth revisiting.

Unfortunately I think this issue will be quite common with our current architecture. Even if we fix the other problem, I'm still envisioning, say... a server crashes, and all the OBS clients reconnect to a different server in the IP round robin. All of those connections will create new stream sessions with the same playbackId, then try and push to the same broadcaster. If I understand this logic correctly, that'll return 500s until the old session ID times out.

The good news is that I bet most of these errors are caused by MistProcLivepeer crashing because of #1665 errors, creating a new stream session, and triggering #1673. So we'll get far fewer of these if we fix that ticket. But we should still figure out how we should respond here.

**Comment by jailuthra** [comment] 2020-12-01 12:04
> Staging and prod are both sharded, but the implication of that is the opposite of what you say here: streams with the same `playbackid` will always be routed to the same shard, meaning the same go-livepeer broadcaster instance. When stream sessions are created, the API server copies the first four characters of the parent's `stream.playbackId` to the child's `stream.id` to ensure that this is the case. Our current prod infrastructure generally has two shards for staging and eight shards for prod, but in all cases separate sessions hit the same B.

Oh that is really helpful to know thanks - and a neat solution to have stickiness between stream and B!

> Unfortunately I think this issue will be quite common with our current architecture. Even if we fix the other problem, I'm still envisioning, say... a server crashes, and all the OBS clients reconnect to a different server in the IP round robin. All of those connections will create new stream sessions with the same playbackId, then try and push to the same broadcaster. If I understand this logic correctly, that'll return 500s until the old session ID times out.

Yupp exactly. These 500s cause MistProcLivepeer to go into a loop of retrying with 0.ts and 1.ts, causing a ton of 500s till the sessionID times out. And when it does it often circles back to #1665 for another 500 :smiley: 

> The good news is that I bet most of these errors are caused by MistProcLivepeer crashing because of #1665 errors, creating a new stream session, and triggering #1673. So we'll get far fewer of these if we fix that ticket.

That's my main hope around this issue as well. Both the 500s form a vicious cycle, and fixing the easier one (1665) that is a clear issue in our system might make it all go away I hope.

>  But we should still figure out how we should respond here.

I was thinking if B could communicate to MistProcLivepeer clearly that it'ss waiting for a previous session to timeout - Mist can theoretically wait for before flooding with new sessions. Some sort of an SLA basically.

But I do feel the 1 minute timeout we have might be too much, and impact the user negatively (who might encounter some failure due to our ingest, and then have 1 minute of downtime even if ingest is back up). 

Maybe 20 seconds is a good timeout for forgetting about the previous session ID - but that depends on how long the user's segments are. For 2s segs it sounds good, for 10s segments not so much.

**Comment by yondonfu** [comment] 2020-12-03 14:21
> I was thinking if B could communicate to MistProcLivepeer clearly that it'ss waiting for a previous session to timeout - Mist can theoretically wait for before flooding with new sessions. Some sort of an SLA basically.

I see the session timeout on B as an internal implementation detail and I think we should try to avoid exposing the HTTP push API consumer to the internal implementation details around session management in B if possible. 

My understanding of the issue is that we want to support multiple streamIDs (external manifestID) for a single playbackID (internal manifestID i.e. the manifestID returned by the webhook), but at the moment, B always indexes into data structs for stream sessions using the playbackID. As a result, as soon as we have two stream sessions with the same playbackID we get a collision.

One takeaway I have from @iameli's [comment](https://github.com/livepeer/go-livepeer/issues/1673#issuecomment-736122922) is that we might be able to avoid this issue if B does not index into stream session data structs using the playbackID since the playbackID will be the same for different streamIDs. His comment suggests returning an `aliases` field in the webhook response - I imagine that the idea here is to return a unique value for the manifestID field in the webhook response so that stream session data structs will be indexed using unique values, but include the playbackID in the aliases field. Then, B could save data under a path using the playbackID so that the data can be fetched at `/stream/playbackId`.

A variant of the above idea is to continue returning the playbackID in the manifestID field of the webhook response, but in `createRTMPStreamIDHandler`, use the streamID extracted from the URL to index into stream session data structs and use the playbackID to create the [storage session](https://github.com/livepeer/go-livepeer/blob/7138591ec3ee61d49afe1f4fa3720539f30c72ae/server/mediaserver.go#L276) so that all data for the streamID will be saved under a path with the playbackID.

I think segment sequence numbering might need to be addressed in both variants. Two stream sessions with different streamIDs might have the same segment sequence numbering, so there would be a collision when storing data for each stream under a path with the same playbackID and sequence number. Perhaps B can re-write sequence numbers of incoming segments by keeping track of the last sequence number for a particular playbackID so that when creating the [HLSSegment](https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver.go#L816), the sequence number is set as the last sequence number + 1?

**Comment by jailuthra** [comment] 2020-12-03 15:37
Thanks for the detailed response @yondonfu !

I like the idea of indexing our internal data structs using streamID and making stream session the first-class citizen, as opposed to playbackID. Both the `aliases` field in the webhook, or extracting streamID from URL at the B side sound good to me. Latter is better as less changes in the webhook side.

> I think segment sequence numbering might need to be addressed in both variants. Two stream sessions with different streamIDs might have the same segment sequence numbering, so there would be a collision when storing data for each stream under a path with the same playbackID and sequence number. 

This sounds perfect to handle the particular issue we're facing with quickly re-opened sessions causing 500s due to the timeout!

But I am still unclear about how it will work for the case the timeout was originally intended for? i.e. if the same user is simultaneously broadcasting from two different sources to the same `playbackID`. Under this segment re-numbering scheme it would lead to weird inter-leaving of the segments of the multiple streams by the user on the same `playbackID`.

I guess we could delete the session for the older streamID when we see a new streamID for the same playbackID, but if the pushAPI-consumer keeps pushing segments for both streamIDs the two might contend and cause multiple deletions.

Or, we could remember old streamID for some time, and ignore segments for those (or send a 500 for those!) so that the pushAPI consumer is still informed that something is not right? WDYT?

**Comment by darkdarkdragon** [comment] 2020-12-03 16:55
@yondonfu @iameli @jailuthra 
> My understanding of the issue is that we want to support multiple streamIDs (external manifestID) for a single playbackID

I want to note that we're only having this problem because:
1. We're using Mist internally for segmenting RTMP stream
2. And we want to playback stream that is being segmented by the Mist from the broadcaster instance - purely to compare Mist playback with our own playback.
In normal usage this shouldn't happen - HTTP push users shouldn't playback stream from broadcaster - they receive transcoded data directly in the response, and playback of the streaming coming through Mist is handled by the Mist itself.

So, when HTTP push handler receives segment with new streamID for which there is already session with the same playbackID - that means that Mist already created new session and old one is not needed anymore - so we could just discard it.

>  if the same user is simultaneously broadcasting from two different sources to the same playbackID

That should be prevented earlier with other mechanisms.

**Comment by iameli** [comment] 2020-12-03 22:08
Just wanted to copy this bit from my proposal in Discord:

> This makes me wonder if there's maybe room in go-livepeer for "stream sessions" to become a first-class construct. If we get a push request that has the same "internal manifest" (aka stream.playbackId) but a different "external manifest" (aka stream.id), then the segment is accepted but treated as a discontinuity in HLS playback via /stream. That could unify the behavior of recording and live playback and also provide a clean answer for the appropriate behavior in #1673.

And

> I'm imagining here - I'm running a 1080p broadcast and my computer's power supply goes out. I pull out my phone and resume the broadcast in 720p portrait mode "hey y'all, sorry, my computer exploded."  Different transcode inputs and outputs entirely. But if we're going to be in the business of providing stable m3u8 URLs based on the playbackId, that's something we need to handle. [...] The most graceful option for us would be to insert a EXT-X-DISCONTINUITY with the new information. https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-4.3.2.3

I think I presently believe that to be the most elegant way to handle new "stream sessions" coming in, especially when there's a reset in the media sequence number. Toss out the old session, insert a `EXT-X-DISCONTINUITY` tag in the HLS output, and proceed with the new session. Don't make any assumptions that the inputs and outputs will be the same, but retain the knowledge that the two sessions are related.

**Comment by darkdarkdragon** [comment] 2020-12-03 23:57
@iameli 
> Toss out the old session, insert a EXT-X-DISCONTINUITY tag in the HLS output, and proceed with the new session.

I like the idea - minimal changes needed, solves problem of quick sessions change

**Comment by jailuthra** [comment] 2020-12-04 10:55
> I think I presently believe that to be the most elegant way to handle new "stream sessions" coming in, especially when there's a reset in the media sequence number. Toss out the old session, insert a EXT-X-DISCONTINUITY tag in the HLS output, and proceed with the new session. 

@iameli I really like this idea from the end-user's perspective of playing back the video without having to refresh their player whenever stream is reset.

I am slightly confused as-to where this tag will go within push API context though. From what I understood push API returns a multi-part of the transcoded mpegts segments for the input segment, and doesn't maintain or worry about the HLS playlist, right?

But yeah this will be a very nice feature for the B's RTMP Ingest -> HLS output workflow for sure!

> And we want to playback stream that is being segmented by the Mist from the broadcaster instance - purely to compare Mist playback with our own playback.

@darkdarkdragon Oh, this is new information for me. Can you give some pointers in the go-livepeer code on how we're doing this? Or does simply playing back from the B's HLS `playbackID` URL work while somebody is pushing on `/live/streamID/0.ts`?

**Comment by darkdarkdragon** [comment] 2020-12-04 14:58
@jailuthra 
> From what I understood push API returns a multi-part of the transcoded mpegts segments for the input segment, and doesn't maintain or worry about the HLS playlist, right?

Yes. But HTTP push API was cut into original RTMP -> segmenting -> transcoding -> HLS playlist workflow of the broadcaster. And so when HTTP push handler receives segment and transcodes it it still gets inserted into HLS playlist and is available for playback that way.

Here
https://github.com/livepeer/go-livepeer/blob/82164f2d626a00dc59e2be9832950ccbefc95c69/server/broadcast.go#L329

source segment received by push handler gets inserted into HLS playlist and is available for playback at /stream/manifestID/source/0.ts url

Here is same for transcoded segments

https://github.com/livepeer/go-livepeer/blob/82164f2d626a00dc59e2be9832950ccbefc95c69/server/broadcast.go#L572

**Comment by jailuthra** [comment] 2020-12-09 14:28
I'm moving to coding up a fix and send a PR soon.

To summarize the discussion in this thread:

1. We don't mind if Mist opens up a new *streamID* session under the same *playbackID* too quickly before previous closed.
2. We should remove the current 500 error thrown. Instead we can close previous *streamID*'s session and open a new one for new *streamID*.
3. We should update the HLS playlist generated at the B to handle the discontinuity in segment sequence number when the session switch happens (even though end user doesn't read this playlist, we do to compare with Mist playback)

The changes in code needed to do this:

- For (1) + (2) we can get the new *streamID* from the URL and return it through `createRTMPStreamIDHandler` and let `HandlePush` do the old session cleanup + new session creation when it happens as noted by Ivan here https://github.com/livepeer/go-livepeer/pull/1672#discussion_r537652544 instead of throwing any error on finding an old session
- For (3) we can set the EXT-X-DISCONTINUITY flag in the already open HLS playlist session if feasible. Our m3u8 library already provides a method `SetDiscontinuity()` for it.

Will move ahead with these changes soon, feel free to comment if I'm missing something!

**Comment by iameli** [comment] 2020-12-10 07:57
Sounds totally reasonable to me. Let's make sure to log the "throwing out old session and creating new one" line specifically so we can pick up if a stream is thrashing between two sessions.

Open question: what happens when someone sends in two RTMP streams with different Mist instances and the same _playbackID_? Because with this current proposal those two sessions would begin an eternal struggle for the HLS output, swapping from segment to segment. That sounds kind of cool to watch but it's undesirable behavior on our end. Possibly something we could combat at the API layer.

**Comment by darkdarkdragon** [comment] 2020-12-10 17:44
> Let's make sure to log the "throwing out old session and creating new one" line specifically so we can pick up if a stream is thrashing between two sessions.

We can even add special metric for it :)

> Because with this current proposal those two sessions would begin an eternal struggle for the HLS output,

Could you elaborate on that? Wouldn't two Mist instances will use two different broadcasters?

**Closed as completed** 2020-12-15 18:50 UTC
Labels: type: bug
