### ISSUE TITLE
"Channel" media player doesn't work unless stream is loaded through player.html

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#229] opened 2017-12-13 16:03 UTC
When starting a new stream, the "Channel" media player does not play the stream until it has first been loaded up on the "player.html" using strmID.

Here is how to recreate:

1. Start broadcasting through a node running in -testnet mode (**not** -offchain) with an Eth address
2. Load up https://media.livepeer.org/channels
3. Enter the Eth address associated with the node.
4. Observe that the player doesn't serve content.
5. Load up https://media.livepeer.org/player.html and load up the manifestID from the stream
6. Observe that the content plays in the player.html
7. Go back to https://media.livepeer.org/channels
8. Enter the Eth address associated with the node.
9. Observe that the player is now serving content :)

**Comment by dob** [comment] 2017-12-13 16:38
1. It's also possible that it just takes 30s-1m before the channel player will be able to find enough segments to begin playing (this could be fixed separately). Could you do a sanity check and see if you start a stream, and then wait a few minutes before trying to play it on either play, and then try the channel player first to see if it works? If not, and these steps still reproduce the issue then....

2. Could you also file an issue in the [Livepeer.js repo issues](https://github.com/livepeer/livepeerjs/issues), referencing this one, since we'll likely need a fix in the repo where the player lives as well?

**Comment by dob** [comment] 2018-01-03 22:48
Fixed in the player. https://github.com/livepeer/livepeerjs/issues/10

**Closed as completed by dob** 2018-01-03 22:48 UTC
Labels: type: bug
