### ISSUE TITLE
Keep ordering consistent in Transcoding Options

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1161] opened 2019-11-04 16:01 UTC
**Is your feature request related to a problem? Please describe.**

As a Broadcaster (B), whenever I am asked to `enter the identifiers of the video profiles [I] would like to use (use a comma as the delimiter in a list of identifiers)`, the list of options always appears in a different sequence.

This makes it complicated to use, as each time I reset it, I have to carefully go through the list and make sure it's selecting the options that I need.

This is exacerbated by the fact that the [Transcoding Options are not persisted between sessions](https://github.com/livepeer/go-livepeer/issues/1159), meaning that I have to set this every time I restart the node.

**Describe the solution you'd like**

I think the best solution, would be to have to key in the actual text for the transcoding option, e.g. like this:

`P144p30fps16x9,P240p30fps16x9,P360p30fps16x9,P720p30fps16x9`

It's not something that I envisage changing very often (without [dynamic on-demand transcoding](https://github.com/livepeer/go-livepeer/issues/1160)), so this more complex way of configuring might not be such an issue... especially if this could be done, as well as [persisting the Broadcaster's Transcoding Options between sessions](https://github.com/livepeer/go-livepeer/issues/1159).

**Describe alternatives you've considered**

A less confusing option compared to the status quo would be to always present the options in the same order, with the same identifiers.

**Comment by j0sh** [comment] 2019-11-04 17:35
Thanks for the report @chrishobcroft  - this is a duplicate of https://github.com/livepeer/go-livepeer/issues/1144 . OK to close this issue?

**Closed as completed** 2019-11-04 22:46 UTC
