### ISSUE TITLE
Network Simulation

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#204] opened 2017-11-28 20:28 UTC
Apply the Swarm team network simulation tool and test the Livepeer p2p network

**Comment by j0sh** [comment] 2019-01-24 05:59
I like the idea of network simulation, however this seems to be a duplicate of https://github.com/livepeer/go-livepeer/issues/170 so I'll leave that one open and close this.

**Closed as completed by j0sh** 2019-01-24 05:59 UTC
