### ISSUE TITLE
B generates a payment that will ensure that minimum credit requirement is met to include with segment

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#897] opened 2019-05-30 01:24 UTC
**PaymentAmount()**

Should return the amount represented by a payment. When using PM, a payment is a ticket and the payment amount is the ticket EV.

**GenPayment(sess, transOpts)**

Should create a payment to be included with a segment to be sent to the orchestrator.

```
minCredit = MinCredit()
currCredit = CurrCredit(self)

paymentValue = 0
if currCredit < minCredit {
    // This will ensure that the orchestrator will at least
    // process the next segment, but the broadcaster technically
    // could send more
    // Note: currCredit can be negative here indicating that
    // the broadcaster needs to pay the orchestrator an amount
    // that covers the owed amount and the minimum credit requirement
    creditGap = minCredit - currCredit
    payAmount = PaymentAmount()
    paymentValue = ceil(creditGap / payAmount) * payAmount
}

// Create a payment for paymentValue
...

UpdateCredit(self, minCredit)

```

**Comment by yondonfu** [comment] 2019-07-10 01:12
This task will be composed of the following changes:

1. Track B's balance for a stream corresponding to a specific manifestID
2. Update `genPayment()` to compute B's credit gap based on its current balance and O's minimum credit (ticket EV)
3. Update `genPayment()` to use B's credit gap to create N tickets to be included in a payment

We can accomplish 1 by adding a `Balance` field to the `BroadcastSession` struct which is already associated with a specific manifestID and O. `genPayment()` can use this field since it already takes a `BroadcastSession` param. I'm leaning toward also returning the payment amount from `genPayment()` i.e.

```
func genPayment(sess *BroadcastSession) (string, *big.Rat, error)
```

The motivation behind returning the payment amount from `genPayment()` is that it can be used to compute B's updated balance after debiting the fee for results later on in `SubmitSegment()`. This updated balance can then be included in the return value for `SubmitSegment()` (would need to nest `net.TranscodeData` in a wrapper struct). Then, the caller of `SubmitSegment()` can use the updated balance when creating a new `BroadcastSession` to be appended to the session list. This follows the approach described in #961 which seeks to avoid mutating the `BroadcastSession` struct - so, instead of mutating the `Balance` field within `SubmitSegment()`, we can just compute the updated balance and include it in the return value for `SubmitSegment()`. We don't need to complete this described workflow for this task though - returning the payment amount in `genPayment()` will suffice.

We can accomplish 2 with something like this piece of pseudocode:

```
func genPayment(sess) (string, *big.Rat, error) {
    ...
    ev := ticketParams.EV()
    if sess.Balance >= ev {
        return "", 0, nil
    }

    creditGap := ev - sess.Balance
    batchSize := round(creditGap) / ev

    // Create batchSize # of tickets
}
```

We can accomplish 3 by adding a `CreateTicketBatch()` method to `pm.Sender` which accepts a `size` param and will create `size` # of tickets which can be encoded in a `TicketBatch` struct in a manner similar to how tickets are encoded in the `Payment` message. This method should be more efficient than calling `CreateTicket()` N times because it will initialize the `TicketBatch` with the ticket params that remain the same across all tickets in the batch and then will only compute the senderNonce and signature N times since they are unique for each ticket.

**Comment by j0sh** [comment] 2019-07-10 06:51
>  This updated balance can then be included in the return value for SubmitSegment() (would need to nest net.TranscodeData in a wrapper struct). Then, the caller of SubmitSegment() can use the updated balance when creating a new BroadcastSession to be appended to the session list

For raw balances (eg, big.Rat) we might need to be careful. It sounds like two concurrent SubmitSegments may potentially overwrite each other's balances if we're doing a get-and-set. (We try not to submit segments concurrently to the same O, but it happens sometimes.) "Last write wins" is OK for `OrchestratorInfo` updates, but balances need stronger mutual exclusion since those are more incremental.

Could we use the new `Balances` object within `core/accounting` ? That looks thread safe, so we can have the BroadcastSession retain a pointer to the `Balances` object [1]. As long as the pointer within BroadcastSession doesn't change, `Balances` can mutate if the API ensures thread safety. That keeps concurrency concerns contained to that corner of the code.

```golang
type BroadcastSession struct {
 ....
  Balances *Balances
  ...
}
```

[1] Or perhaps a `Balance` subset that calls down to `Balances` - mitigates the extra manifestID argument which might not be strictly necessary for BroadcastSession. Very minor though.

**Comment by kyriediculous** [comment] 2019-07-10 14:37
> Could we use the new Balances object within core/accounting ? That looks thread safe, so we can have the BroadcastSession retain a pointer to the Balances object [1].

I like this because then we're avoiding code duplication of calculating updated balances and we make sure the methodologies are uniform between B and O. 

> The motivation behind returning the payment amount from genPayment() is that it can be used to compute B's updated balance after debiting the fee for results later on in SubmitSegment()

If we were to use core/accounting , wouldn't it be simpler to not change function signatures and credit the generated payment amount (`TicketParams.EV() * n` ) to the balance in`genPayment` as it takes the session as an argument? 


Later on in `SubmitSegment` we can debit from this balance using the `Balances.Debit` method.

If we want to keep `BroadcastSession` immutable we can copy over the pointer to the new session. 

The downside , as Josh mentioned, is that having to pass `ManifestID` to a mapping that would only contain 1 key anyway feels a bit redundant. 

To work around this however, couldn't we export `type balance` and use the mutex that is now in `type Balances` inside of `balance` instead, because currently we're also locking the entire map which might not be optimal? We could then point the receiver methods to a single balance rather than the wrapper struct `Balances`. 

The wrapper `Balances` could then still be used for O, but we could use the subset `Balance` for the broadcastSessions instead. 

**EDIT:** This might not be possible due to the same reason described here https://github.com/livepeer/go-livepeer/pull/904#discussion_r290972372

> We can accomplish 3 by adding a CreateTicketBatch()

I think we can also safely remove CreateTicket() then ? As a single ticket payment would just be a call to CreateTicketBatch() where `n=1`

**Comment by yondonfu** [comment] 2019-07-10 17:07
@j0sh 

> It sounds like two concurrent SubmitSegments may potentially overwrite each other's balances if we're doing a get-and-set. (We try not to submit segments concurrently to the same O, but it happens sometimes.)

Hm could you point me to the code that allows for concurrent segment submission to the same O? From a skim of the code, I was under the impression that we would only submit the next segment to O once the session for that O becomes available again (i.e. after the last submission completes and the session is added back to the list), but I might've missed the relevant code. 

> It sounds like two concurrent SubmitSegments may potentially overwrite each other's balances if we're doing a get-and-set.

So, we can avoid this by tracking values using the `Balances` struct, but if two concurrent segment submissions are possible then it's also possible for segment 2 to be submitted with an outdated balance because the balance update for segment 1 was not picked up yet. Will need to think about this.

@kyriediculous 

> If we were to use core/accounting , wouldn't it be simpler to not change function signatures and credit the generated payment amount (TicketParams.EV() * n ) to the balance in genPayment as it takes the session as an argument?

That was actually my original plan, but I am concerned about crediting the balance in `genPayment()` and then encountering an error later on in `SubmitSegment()` prior to the actual segment being uploaded (along with its headers) to O. In this scenario, we would remove the session and on the next refresh the session would be created with the same manifestID and since it contains a pointer to the same underlying `Balances` struct, the balance from the last session will be persisted. However, if the segment and its headers were never sent to O, then B and O's balances would be out of sync. So, I think it would be better to only update B's balance if we know the segment has been submitted.

> I think we can also safely remove CreateTicket() then ? As a single ticket payment would just be a call to CreateTicketBatch() where n=1

Yep.

**Comment by kyriediculous** [comment] 2019-07-10 17:21
> That was actually my original plan, but I am concerned about crediting the balance in genPayment() and then encountering an error later on in SubmitSegment() prior to the actual segment being uploaded (along with its headers) to O

That's a very fair concern indeed. The only way to circumvent this I think is encoding the payment header outside of `genPayment` so we can access the EV and len(TicketSenderParams) but then simply returning an extra value instead is likely to be a better solution 👍 .

**Comment by j0sh** [comment] 2019-07-11 04:47
> Hm could you point me to the code that allows for concurrent segment submission to the same O? 

Here I'm referring to having two concurrent segments *in flight* to the same O. Looked at this closely today and while I haven't been able to reproduce the issue, it does seem to be a side effect of the session refresh behavior in capacity-constrained environments. The sequence would be something like this:

1. B submits a segment
2. B errors out locally for some reason, removes O from list
3. B refreshes O list
4. O gets re-inserted in list with same manifest ID
5. B submits another segment to O.
6. Sometimes O is still busy with the first segment - OrchestratorBusy

(Whether we should close this loophole is probably another discussion we could have at some point, probably by generating a fresh manifest ID per refreshed session.)

My specific concern was around the original proposal of doing a full session+balance replacement, rather than a delta update of the balance itself. Something like:

1. B submits segment S1 with balance B1
1. B submits segment S2 with balance B1 (not necessarily simultaneously)
1. B receives S1 response with X pixels, updates balance to B2 = B1 - X by recreating the original session object and the balance value
1. B receives S2 response with Y pixels, updates balance to B3 = B1 - Y by recreating the original session object and the balance value

The approach of using the `Balances` struct mostly mitigates that issue by offering a shared view of the current balance and doing delta updates, but there are some more (admittedly distant) concerns I'll outline below.

> if two concurrent segment submissions are possible

It's unlikely that we'll actually be *generating* tickets for concurrent segments to the same O simultaneously, as long as we stipulate this is for "segmented, live video" where we expect segments to come in at a reasonable interval. This assumption is deeply baked into other parts of the design, so I think it's OK if the simplest approach for updating the balance builds off that. However, this feels like something that's rather easy to lose sight of, so we probably should document it somewhere in case we're reviewing things to support other types of workflows.

>  it's also possible for segment 2 to be submitted with an outdated balance because the balance update for segment 1 was not picked up yet

Yes, there is a risk if there are concurrent in-flight segments. In particular, we credit for tickets generated, but that credit should be immediately 'spent' (debited) until we get a response from the O. Otherwise, subsequent segments may try to claim the credit for themselves before a response is received. After the response, we can credit the "change" back in. I think a safer flow would look something like this (in units of EV):

* B starts with credit 0EV.
* Submits segment S1 worth 1.5EV . Generates 2 tickets and credits 2EV, but immediately 'debits' that 2EV, so the balance should still be 0.
* Receive response to S1 confirming 1.5EV expense.
* Credits the change (2EV - 1.5EV = 0.5EV). New balance 0.5EV
* Submits segment S2 worth 1.5EV. Generates 1 ticket, credits 1EV, debits 1.5EV (1 EV ticket + 0.5EV previous balance). New balance is 0.
* Suppose another segment S3 comes in while S2 is still processing. Since the balance is 0, generate 2 tickets, credit 2EV, debit 2 EV. New balance is again 0.
* Receive response to S2 confirming 1.5EV expense. Since the debit for S2 was 1.5EV, there is no change and balance is again 0.
Receive response to S3 confirming 1.5EV expense. Since the debit for S3 was 2EV, the change is 0.5 and the balance is now 0.5.

The important bits here in terms of concurrency: 
* We have a shared and reasonably up-to-date view of the balance.
* Balance updates should be incremental delta updates, not resets.
* As long as we're not generating tickets and updating balances for several segments at the exact same instant, we're likely OK. (This is also probably solvable through a very specific API in Balances, something like `returnNumTicketsAndUpdateBalanceGivenThisAmountToCover(amount)`)
* The value of the segment should be debited prior to submission, regardless of the number of tickets generated. So if we have a credit of 0.5EV, a segment worth 1.5EV, we generate a 1EV ticket and debit 1.5 EV.

> I am concerned about crediting the balance in genPayment() and then encountering an error later on in SubmitSegment()

If we credit (and corresponding debit) for a segment then an error occurs, that should probably be considered 'spent' unless we're reasonably certain the O did not receive the ticket.

Anyway, I don't think any of this is necessarily something that needs to be done immediately but it was helpful for me to think through things. There may be a simpler approach.

**Comment by yondonfu** [comment] 2019-07-11 16:22
Thanks for the write-up!

> Here I'm referring to having two concurrent segments in flight to the same O

Got it - good to know about the behavior.

> My specific concern was around the original proposal of doing a full session+balance replacement, rather than a delta update of the balance itself

Got it - yeah I understand the concern and I think using the concurrency safe `Balances` struct to persist balances is the best path forward.

> Yes, there is a risk if there are concurrent in-flight segments

So, the two scenarios where outdated balances can be a concern are:

1. Concurrent in-flight segments (which implies one segment was submitted prior to receiving a response for the other)
2. Concurrent segment submission (which also implies one segment was submitted prior to receiving a response for the other)

2 isn't as much of a concern right now since other parts of our system already assume a "live" context where segments come in at a reasonable interval.

1 is possible today when refreshing sessions in a capacity constrained environment. While we could remove 1 as a concern by strictly enforcing one segment in flight per manifestID, it is probably best not to have the balance maintenance logic depend too much on this behavior if possible.

> I think a safer flow would look something like this (in units of EV)

This is pretty similar to a design I started thinking about except in my design B would only reserve the payment amount (`EV * ceil(creditGap / EV)`) for a segment. I like your design better - B would reserve its current credit + the payment amount for a segment which ensures that credit is never "shared" between multiple segments because the credit reserved for each segment is computed independently.

> The value of the segment should be debited prior to submission

This sentence seems to imply that B will be able to estimate the value of a segment prior to submitting it i.e. estimate the output pixels and if we track decoding costs later on this would include input pixels as well. I like this is as goal to run at down the line.

In the short term, with B *not* estimating the value of a segment prior to submitting I think using this "change" based design is still helpful.

Currently, I see the following options:

1. "Change" based design with B targeting at least EV of credit for each segment
2. "Change" based design with B targeting at least maxEV of credit for each segment
3. "Change" based design with B targeting at least the value of a segment for each segment

We're currently doing option 1. The edge case here is if there are concurrent segments in flight and the fee for a segment exceeds EV.

Ex.

B's PoV:

1. Balance = 0EV
2. Submit segment 1 with EV
3. While segment 1 is in flight, submit segment 2 with EV

O's PoV:

1. Receive segment 1 and credit B's balance so that it is EV
2. Debit 1.5EV fee from B's balance so that it is -.5EV
3. Receive segment 2 and credit B's balance so that it is -.5EV + EV = .5EV
4. B's balance is insufficient (< EV) so O returns an error

We can make this example scenario less likely with option 2. Instead of B calculating the payment amount based on a minimum credit of EV, it calculates the payment amount based on its maxEV which is >= EV. This results in payments that provide a bit more breathing room in the case of concurrent in-flight segments.

Ex.

Suppose maxEV = 2EV

B's PoV:

1. Balance = 0EV
2. Submit segment 1 with 2EV
3. While segment 1 is in flight, submit segment 2 with 2EV

O's PoV:

1. Receive segment 1 and credit B's balance so that it is 2EV
2. Debit 1.5EV fee from B's balance so that it is .5EV
3. Receive segment 2 and credit B's balance so that it is .5EV + 2EV = 2.5EV
4. B's balance is sufficient (> EV) so O proceeds with transcoding

Perhaps this strategy would make sense if B wants to avoid insufficient balance errors in a setting where concurrent in-flight segments are prevalent. I don't think we need to go down this route at the moment though.

Ultimately, if we move to option 3 and short-circuit transcoding then this edge case scenario will no longer be a concern since B's balance will never be negative (O stops transcoding prior to the fee exceeding the balance) and it is up to B to properly estimate the credit required for transcoding to complete.

> If we credit (and corresponding debit) for a segment then an error occurs, that should probably be considered 'spent' unless we're reasonably certain the O did not receive the ticket.

I think we can only be certain that O did not receive the payment when `SubmitSegment()` returns an error while [preparing the HTTP request](https://github.com/livepeer/go-livepeer/blob/master/server/segment_rpc.go#L261). Besides this error, we can't be certain that O did not receive the payment so we can just consider the credit "spent"

**Closed as completed** 2019-07-16 01:25 UTC
