### ISSUE TITLE
Output Stream DTS Doesn't Match Timestamp

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#803] opened 2019-03-28 01:10 UTC
**Describe the bug**
The output stream timestamp is sometimes off.  This causes the video to skip.

**To Reproduce**
1. Run a transcoding setup, stream a RTMP stream into the ingest node.
2. Try to store one of the transcoded renditions locally using ffmpeg.  For example: `ffmpeg -i http://35.243.231.237:9201/stream/ericID/P240p30fps16x9.m3u8 -c:v copy -c:a copy livepeer_dump.mp4`
3. ffmpeg should report an error: `Non-monotonous DTS in output stream 0:1`

**Expected behavior**
Output DTS to match.

**Comment by j0sh** [comment] 2019-03-29 19:38
Curious, what client was this broadcasting with? Any special settings for the source stream? Tried with OBS and wasn't able to reproduce within a few minutes.

**Comment by j0sh** [comment] 2019-04-05 17:59
Was able to reproduce this. Some observations:

* This affects only audio streams
* The discontinuity is at segment boundaries; the first audio frame of the current segment overlaps with the last frame of the previous segment

![image](https://user-images.githubusercontent.com/292510/55645208-ce518e00-578c-11e9-8d66-8efc668013a4.png)

* The first audio pts of a given transcoded segment is off by exactly one frame.

Eg, for a source segment starting at pts `t`, with a duration of `d`, the first transcoded audio frame would have a pts of `t-d`. The transcoded pts of `t-d` is typically very close to the pts of the last frame in the previous transcoded segment, and it overlaps sometimes (maybe due to rounding from internal timebase conversion).

* There is an extra frame after each transcode of AAC. This is the overlapping first frame.
* The extra frame and pts adjustment comes from the encoder itself, rather than the decoder or filters.
* Some inspection of the ffmpeg source code reveals this: 
```c
    /**
     * Audio only. The number of "priming" samples (padding) inserted by the
     * encoder at the beginning of the audio. I.e. this number of leading
     * decoded samples must be discarded by the caller to get the original audio
     * without leading padding.
     *
     * - decoding: unused
     * - encoding: Set by libavcodec. The timestamps on the output packets are
     *             adjusted by the encoder so that they always refer to the
     *             first sample of the data actually contained in the packet,
     *             including any added padding.  E.g. if the timebase is
     *             1/samplerate and the timestamp of the first input sample is
     *             0, the timestamp of the first output packet will be
     *             -initial_padding.
     */
    int initial_padding;
```
https://github.com/FFmpeg/FFmpeg/blob/772c73e61f5df3b37b4b227bdf8e93035f8f7daa/libavcodec/avcodec.h#L3069-L3084

* Further follow-ups surfaced this issue: https://trac.ffmpeg.org/ticket/2828

This phenomenon is called "decoder delay" or a "preroll audio frame" and is normal under most circumstances. More information here: https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFAppenG/QTFFAppenG.html

The reason this behavior affects us (and not other HLS transcoders) is because we process each segment with a fresh transcoder, rather than preserving the state of the transcoder between segments. There's a few paths forward from here:

* Drop the preroll frame in question.
  * Seems to decode OK with ffmpeg (both from playlist and standalone ts) but need to check if it causes audible issues.
* Adjust start time to be one frame ahead.
  * May lead to slightly out-of-sync AV since the audio will be one frame ahead of where it should be.
* Ignore this issue entirely since we're moving to codec copy for audio.
  * This just punts the issue until later. We'll still have this bug in the codebase, and it'll probably end up being re-discovered, re-diagnosed the hard way.
* Preserve the state of the transcoder in between segments.
  * This is a lot of work. Also unclear how this would work when transcoding discontinuous segments, eg round-robin.
  * We might end up going down this path anyway to close the LPMS performance gap between ffmpeg (per-segment overhead accounts for 50% of the slowdown) and to lower latencies (eg, CMAF).
* Leave it as-is.
  * Other than ffmpeg complaining during recording, are there playback issues? FFplay doesn't throw a warning.

**Closed as completed** 2019-04-11 21:50 UTC
