### ISSUE TITLE
Fix TestSubmitSegment_Timeout

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1793] opened 2021-03-12 11:31 UTC
**Describe the bug**
Timing issues in this test keep breaking CI 

https://github.com/livepeer/go-livepeer/blob/b68bf164afc195cebe9d89e0782b4a61eba2d7fe/server/segment_rpc_test.go#L1793

```
--- FAIL: TestSubmitSegment_Timeout (0.53s)
    segment_rpc_test.go:1845: 
        	Error Trace:	segment_rpc_test.go:1845
        	Error:      	Expected nil, but got: &fmt.wrapError{msg:"header timeout: Post \"https://127.0.0.1:44427/segment\": context deadline exceeded", err:(*url.Error)(0xc001da5e00)}
        	Test:       	TestSubmitSegment_Timeout
```

To Reproduce 

```
go test -timeout 30s  -run ^TestSubmitSegment_Timeout$ github.com/livepeer/go-livepeer/server -count=100
```

**Comment by yondonfu** [comment] 2021-12-30 15:34
Duplicate of #2145

**Closed as completed by yondonfu** 2021-12-30 15:34 UTC
Labels: type: bug
