### ISSUE TITLE
B unable to process RTMP content from ManyCam (iOS / Android)

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1423] opened 2020-03-13 13:51 UTC
**Describe the bug**

When streaming using ManyCam on Android / iOS to stream RTMP into Livepeer in `-broadcaster` mode, the B is unable to process the content, reporting 

**To Reproduce**

1. Download latest livepeer binary:
```
wget https://github.com/livepeer/go-livepeer/releases/download/v0.5.5/livepeer-linux-amd64.tar.gz
```
2. Unzip binaries:
```
tar -xzf livepeer-linux-amd64.tar.gz
```
3. Validate the version:
```
./livepeer-linux-amd64/livepeer -version
```
4. Observe the version:
```
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```
5. Run an Orchestrator with the following command:
```
./livepeer-linux-amd64/livepeer -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -orchSecret secret -v 99
```
6. Run a Transcoder with the following command:
```
./livepeer-linux-amd64/livepeer -transcoder -cliAddr 127.0.0.1:7937 -httpAddr 127.0.0.1:8937 -orchAddr 127.0.0.1:8936 -orchSecret secret -v 99
```
7. Run a Broadcaster with the following command:
```
./livepeer-linux-amd64/livepeer -currentManifest -orchAddr :8936 -rtmpAddr 0.0.0.0 -transcodingOptions P360p30fps16x9,P240p30fps16x9 -v 99 -broadcaster
```
8. Use `FFmpeg` to publish RTMP content into the B
```
ffmpeg -re -f lavfi -i testsrc=size=640x480:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 10000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_josh_from_ffmpeg
```
9. Validate the the B is serving Transcoded content:
```
curl http://127.0.0.1:8935/stream/current.m3u8
```
10. Previous command should return:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=640x480
hello_josh_from_ffmpeg/source.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1200000,RESOLUTION=640x360
hello_josh_from_ffmpeg/P360p30fps16x9.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=600000,RESOLUTION=426x240
hello_josh_from_ffmpeg/P240p30fps16x9.m3u8
```

11. Stop the Publisher process started in step 8.

12. Stream from OBS using Customer Server `rtmp://127.0.0.1:1935` (keyframe interval = 1s)

13. Validate the the B is serving Transcoded content:
```
curl http://127.0.0.1:8935/stream/current.m3u8
```
14. Previous command returns:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=1280x720
hello_josh_from_obs/source.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=1200000,RESOLUTION=640x360
hello_josh_from_obs/P360p30fps16x9.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=600000,RESOLUTION=426x240
hello_josh_from_obs/P240p30fps16x9.m3u8
```
15. Stream into B from ManyCam
16. Observe the B receiving a stream, but failing with:
```
Video Created With ManifestID: hello_josh_from_manycam

I0313 18:49:05.637752   25688 lpms.go:149] Segment RTMP Req: rtmp://127.0.0.1:1935/stream/hello_josh_from_manycam/5eb5ede116ec
I0313 18:49:05.639597   25688 player.go:63] LPMS got RTMP request @ rtmp://127.0.0.1:1935/stream/hello_josh_from_manycam/5eb5ede116ec
I0313 18:49:19.523529   25688 player.go:105] LPMS got HTTP request @ /stream/current.m3u8
E0313 18:49:25.782851   25688 lpms.go:174] Error polling Segment: SegmenterTimeout, Retrying
E0313 18:49:26.283129   25688 lpms.go:174] Error polling Segment: SegmenterTimeout, Retrying
E0313 18:49:26.784335   25688 lpms.go:200] Error segmenting stream: SegmenterTimeout
I0313 18:49:26.784404   25688 basic_rtmp_videostream.go:163] Closing RTMP hello_josh_from_manycam/5eb5ede116ec
E0313 18:49:26.784600   25688 basic_rtmp_videostream.go:135] Error reading packet from RTMP: read tcp 192.168.2.112:1935->192.168.2.101:42902: use of closed network connection
I0313 18:49:26.784678   25688 mediaserver.go:461] Ended stream with id=hello_josh_from_manycam
I0313 18:49:26.785818   25688 video_segmenter.go:242] Cleaning up video segments.....
```
17. Run the `curl` command again
```
curl http://127.0.0.1:8935/stream/current.m3u8
```
18. Observe a `ErrNotFound` error from `curl`.

**Expected behavior**

I expect that Livepeer running in `-broadcaster` mode should be able to accept and process RTMP content from any number of different RTMP publishing software suites.

**Environmentals**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```
```
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```
```
Android version 10
```
```
ManyCam version 1.10.0o
```

**Other information**

This behaviour with `Error polling Segment: SegmenterTimeout, Retrying` has been observed:

- On Livepeer running on:
  - local Ubuntu OS
  - 2 independently built hosted Ubuntu OS instances

- With other RTMP publishing software:
  - ManyCam on Android
  - ManyCam on iPhone
  - DJI Mavic Pro Drone Livestreaming software (when running in manual video mode, not when running in automatic video mode)
  - Mevo livestreaming camera device

**Full session logs**

[Broadcaster Logs - ManyCam Debugging.txt](https://github.com/livepeer/go-livepeer/files/4329865/Broadcaster.Logs.-.ManyCam.Debugging.txt)

[Orchestrator Logs - ManyCam Debugging.txt](https://github.com/livepeer/go-livepeer/files/4329866/Orchestrator.Logs.-.ManyCam.Debugging.txt)

[Transcoder Logs - ManyCam Debugging.txt](https://github.com/livepeer/go-livepeer/files/4329867/Transcoder.Logs.-.ManyCam.Debugging.txt)

**Comment by yondonfu** [comment] 2020-03-15 21:26
Thanks for the report!

Looks like this may be related to livepeer/lpms#135.

**Comment by yondonfu** [comment] 2020-04-27 13:00
It appears that this issue was not caused by the LP node, but by ManyCam not sending any keyframes. See the following Discord conversation:

```
chrishobcroft 03/20/2020
For anyone following this thread, @f1l1b0x and I have identified the issue, and have informed ManyCam support. They are yet to respond.

dob 03/20/2020
Niiicee. What was the issue? Something that Livepeer doesn't handle (but should), or ManyCam android doing something unconventional?

chrishobcroft03/20/2020
ManyCam not sending any keyframes.
```

Closing this issue since there is no changes requires for the LP node.

**Closed as completed by yondonfu** 2020-04-27 13:00 UTC
Labels: type: bug, area: broadcasting
