### ISSUE TITLE
Add an RPC fallback in flag setting

### ISSUE THREAD

**Issue by Franck-UltimaRatio** [livepeer/go-livepeer#2632] opened 2022-10-22 07:42 UTC
when our L2 RPC has an outage our nodes loose all there jobs.

Add the possibility to add at least one RPC L2 fallback Flag in livepeer config

Really usefull also if you need to do some maintenance on your own RPC. Yours nodes will automaticly switch to fallback RPC without loosing jobs, then go back to main RPC when done.

**Comment by iameli** [comment] 2022-10-23 20:00
I think this would be a pretty solid feature, but in the meantime you can make something very similar happen with [Dshackle](https://github.com/emeraldpay/dshackle) in ["fallback" mode](https://github.com/emeraldpay/dshackle/blob/fa59d5570ed507a3b5aceeaa50162337bd42f654/docs/04-upstream-config.adoc#roles-and-fallback-upstream).

**Comment by AuthorityNull** [comment] 2022-10-24 00:25
> I think this would be a pretty solid feature, but in the meantime you can make something very similar happen with [Dshackle](https://github.com/emeraldpay/dshackle) in ["fallback" mode](https://github.com/emeraldpay/dshackle/blob/fa59d5570ed507a3b5aceeaa50162337bd42f654/docs/04-upstream-config.adoc#roles-and-fallback-upstream).

Does Dshackle support Arbitrum? I'm not seeing it on their supported Blockchain list, unless it's included with the eth support.

**Comment by leszko** [comment] 2022-10-24 06:48
Duplicate of #1959

**Closed as completed by leszko** 2022-10-24 06:48 UTC
Labels: status: triage
