### ISSUE TITLE
Error when running with `initializeRound`

### ISSUE THREAD

**Issue by ericxtang** [livepeer/go-livepeer#1294] opened 2020-01-12 03:45 UTC
**Describe the bug**
When running the following command on the Rinkeby network `./livepeer -network rinkeby -orchestrator -transcoder -serviceAddr 127.0.0.1:8935 -orchAddr 0.0.0.0 -initializeRound true -pricePerUnit 40000 -nvidia 0`, you get a 
```
panic: Price per unit of pixels must be greater than 0, provided 0 instead
```

But if you run `./livepeer -network rinkeby -orchestrator -transcoder -serviceAddr 127.0.0.1:8935 -orchAddr 0.0.0.0 -pricePerUnit 40000 -nvidia 0` (remove the `-initializeRound true` portion), it works fine.

**To Reproduce**
1. Download [0.5.2]( https://build.livepeer.live/0.5.2-80db367f/livepeer-linux-amd64.tar.gz)
2. Click on run the first and second command

**Expected behavior**
Both commands should work.

**Comment by yondonfu** [comment] 2020-01-12 16:44
The CLI flag syntax `-initializeRound true` is actually [not permitted by the Go flag package](https://golang.org/pkg/flag/) since `-initializeRound` is a boolean flag. In order to set the value for this flag you have to use the syntax `-initializeRound` or `-initializeRound=true`.

For now, we can make sure that docs that describe commands containing boolean flags always use permitted syntax for the boolean flags (i.e. `-flag=true` or `-flag`).

**Comment by yondonfu** [comment] 2020-01-14 16:34
Going to close this because the problem described is expected behavior with the current flag parsing library that the node uses. If we want to change that behavior we'd have to consider changing the flag parsing library used which is left for a separate discussion.

**Closed as completed by yondonfu** 2020-01-14 16:34 UTC
Labels: type: bug
