### ISSUE TITLE
Error getting pending stake: abi: improperly formatted output

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/go-livepeer#1158] opened 2019-11-04 12:33 UTC
**Describe the bug**

After registering as an Orchestrator, and before becoming active, errors appear in the `livepeer` console and in the `livepeer_cli` output whenever calling `1. Get node status`.

This issue stops happening when the node becomes active

**To Reproduce**
0. Run `livepeer -orchestrator -transcoder`
1. Invoke (and complete) the multi-step process of becoming an orchestrator
2. Call `1. Get node status` _before the next round starts_.
3. See this error in the `livepeer_cli` output:
```
ERROR: logging before flag.Parse: E1104 12:04:50.321334   29282 wizard_stats.go:220] Error getting delegator info: unexpected end of JSON input
```
4. See this error in the `livepeer` console:
```
E1104 11:57:08.656475   29270 client.go:640] Error getting pending stake: abi: improperly formatted output:�y� (end round must be after last claim round - Bytes: [[8 195 121 160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 40 101 110 100 32 114 111 117 110 100 32 109 117 115 116 32 98 101 32 97 102 116 101 114 32 108 97 115 116 32 99 108 97 105 109 32 114 111 117 110 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
E1104 11:57:08.656508   29270 webserver.go:672] abi: improperly formatted output:�y� (end round must be after last claim round - Bytes: [[8 195 121 160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 40 101 110 100 32 114 111 117 110 100 32 109 117 115 116 32 98 101 32 97 102 116 101 114 32 108 97 115 116 32 99 108 97 105 109 32 114 111 117 110 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
```

**Expected behavior**

That whatever the logic is, it is built to handle all scenarios, especially one which occurs so close to the start of an Orchestrator's operation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version:
```
Livepeer Node Version: 0.5.0
Golang runtime version: gc go1.13
Architecture: amd64
Operating system: linux
```

**Comment by yondonfu** [comment] 2019-11-04 15:53
@chrishobcroft Thanks for the report! Looks like this is a duplicate of #1145 so let's track this issue there!

**Closed as completed by yondonfu** 2019-11-04 15:53 UTC
