### ISSUE TITLE
Winning ticket created with bad creationRound

### ISSUE THREAD

**Issue by Franck-UltimaRatio** [livepeer/go-livepeer#2610] opened 2022-10-01 09:01 UTC
We got a ticket this night but it can't be redeemed with this error :

  |   | 2022-10-01 10:53:14 | E1001 04:53:14.477719 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:52:54 | E1001 04:52:54.624741 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:52:34 | E1001 04:52:34.335059 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:52:24 | E1001 04:52:24.475095 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:52:04 | E1001 04:52:04.686225 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:51:54 | E1001 04:51:54.431712 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:51:44 | E1001 04:51:44.559290 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:51:24 | E1001 04:51:24.630980 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"
  |   | 2022-10-01 10:51:04 | E1001 04:51:04.422044 2174140 queue.go:149] Error redeeming err="execution reverted: ticket is expired"

In the database, this ticket appear to been created during round 2713, but it has been created during round 2716.

![ticket not redeemed](https://user-images.githubusercontent.com/87469831/193401869-75de4945-95f8-4ee0-b5a9-a1afa20819c3.jpg)

The node is running under linux with latest livepeer release (0.5.34)

**Comment by Franck-UltimaRatio** [comment] 2022-10-02 08:44
I think there was the same problem with the previous ticket. I think it was created during round 2714, and yet it also appears to have been created during round 2713. But it was still redeemed because it was not beyond 2 rounds.
For the moment, we have reset the node, and we have erased the database.

**Comment by leszko** [comment] 2022-10-03 10:19
Interesting, seems like both B and O would be connected to the RPC providers which are not in sync 🤔 @yondonfu any thoughts why it might have happened? 

I would check if we encounter more situations like this.

**Comment by Franck-UltimaRatio** [comment] 2022-10-03 12:39
fyi, we are using as rpc provider, Cloudflare as loadbalancing, with a mix of arb1 and alchemy rpc endpoint. And we did not encounter this problem with our other node for the moment. still waiting for a new winning ticket on  NYC node to see if error is fixed or not.

**Comment by Franck-UltimaRatio** [comment] 2022-10-04 06:32
For information, after restarting the node and erasing the database, the last two winning tickets were correctly created.

![image](https://user-images.githubusercontent.com/87469831/193750114-28f9d4b1-f843-4e98-8ca0-901633efee0f.png)

I kept a copy of the old database if needed.

**Comment by leszko** [comment] 2022-10-05 14:42
Closing, since it's hard to reproduce this issue. @Franck-UltimaRatio please reopen if you encounter this again and have steps to reproduce.

**Closed as completed by leszko** 2022-10-05 14:42 UTC
Labels: need: investigation, area: orchestrator QoL, area: blockchain
