### ISSUE TITLE
Reward not paid during unbonding

### ISSUE THREAD

**Issue by Pet222** [livepeer/go-livepeer#1018] opened 2019-08-05 14:29 UTC
**Describe the bug**
When a node is not claiming reward or not paying the reward for staking an unbonding was initiated to an other node. During the unbonding period the node who did not pay the reward claims the reward but it will not be payed out for staking. It seems in this case the reward is lost during unbonding.

**To Reproduce**
- in round 1438 transcoder https://explorer.livepeer.org/accounts/0x525419ff5707190389bfb5c87c375d710f5fcb0e/transcoding claimed the reward very late. Therefore after round 1438 I initiated a bounding to an other transcoder. I see that by now the node https://explorer.livepeer.org/accounts/0x525419ff5707190389bfb5c87c375d710f5fcb0e/transcoding was claiming the reward but I do not got the reward from the node despite I was staking the node in round 1439.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dob** [comment] 2019-08-05 16:42
Thanks for the report on this. This is actually a known behavior, due to implementation details and the tradeoffs of doing all the state account in Ethereum. In short:

* After you have "claimed rewards and fees" for a round as a delegator, you can no longer claim rewards and fees for that same round.
* Changing your delegation status - bonding more, bonding towards a different node, unbonding, etc - automatically claims rewards and fees for all rounds up until the current round.
* And hence, if the delegate calls reward after you have claimed for that round (by moving your stake), you will not be able to access your portion of the reward for that round.

The actionable step a delegator could live by to truly optimize would be: only change your delegation in the final block of a round.

The more reasonable step would be: Prefer delegation towards nodes who reliably call reward early in the round.

And the eventual goal should be: the protocol architecture and Ethereum state accounting make this a non issue. But of all the challenges and priorities facing the protocol scalability and development, this may not be urgently prioritized. We'd certainly welcome architecture designs and implementation candidates to review if anyone takes this on.

**Comment by yondonfu** [comment] 2020-07-17 18:48
Closing this because this is expected behavior right now. Changes to the expected behavior can be documented in a separate issue (probably in livepeer/protocol or livepeer/LIPs).

**Closed as completed by yondonfu** 2020-07-17 18:48 UTC
