### ISSUE TITLE
StartBackfillBlockDepth config param for blockwatch package

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1149] opened 2019-11-01 18:01 UTC
**Is your feature request related to a problem? Please describe.**

The `blockwatch` package has a `BackfillEventsIfNeeded()` function which backfills events from the last retained block on the stack maintained by the package. If no last retained block is on the stack (eg. for a new node), backfilling will not happen and the blockwatcher will just start watching for events from the latest block.

With updates to active O set tracking there is a need for a synchronization operation, whereby a node replays all past `TranscoderActivated` and `TranscoderDeactivated` events to establish the current active set. 

To accomodate such synchronization the blockwatcher needs a feature that allows it to start backfilling events starting at block N instead. 

**Describe the solution you'd like**

1. Add a `StartBackfillBlockDepth` field to `blockwatch.Config` supplied to the constructor

2. Set `startBlock` to backfill events from based on whether `StartBackfillBlockDepth` is defined

**Comment by yondonfu** [comment] 2019-11-04 16:56
Looks like this is a duplicate of go-livepeer#1149 - can we close this?

**Closed as completed** 2019-11-13 21:57 UTC
