### ISSUE TITLE
Password issue connecting remote T to O

### ISSUE THREAD

**Issue by Pon-node** [livepeer/go-livepeer#2452] opened 2022-06-08 20:42 UTC
**Describe the bug**
I was not able to connect remote transcoder to my orchestrator due to -orchSecret having the ? symbol 

**To Reproduce**
1. Add the ? At -orchSecret orchsecret?
**Expected behavior**
Remote transcoder will not connect to orchestrator

**Comment by thomshutt** [comment] 2022-07-22 10:11
@Pon-node What exactly is the failure you see here? My shell complains about the question mark: ```zsh: no matches found: secre?``` but when I quote with `-orchSecret "secre?"`, it seems to work fine on zsh / MacOS

**Comment by Pon-node** [comment] 2022-07-22 21:36
@thomshutt It's been a wile now... Orchestrator was on ubuntu and transcoder was using windows.

**Comment by thomshutt** [comment] 2022-07-25 09:06
@Pon-node Any chance you can try to reproduce again? Otherwise I think we'll have to close this, since it's not happening locally for me

**Comment by thomshutt** [comment] 2022-08-01 10:47
Going to close this for now. Feel free to reopen if you see the issue again

**Closed as completed by thomshutt** 2022-08-01 10:47 UTC
Labels: type: bug, status: core contributors working on it, area: orchestrator QoL, status: blocked
