### ISSUE TITLE
Change how invoke multistep/bond/unbond lpt is read by livepeer_cli

### ISSUE THREAD

**Issue by RyanC92** [livepeer/go-livepeer#2187] opened 2022-01-16 14:58 UTC
**Is your feature request related to a problem? Please describe.**
when bonding or invoking to become an orchestrator, you have to know that your input for 10LPT is "1000000000000000000" to any newcomer or old timer, this is extremely confusing and programatically I believe this could easily be solved.

**Describe the solution you'd like**
Change the way the program reads the input, 10 LPT should be 10 LPT. .5 lpt should be .5. 

If 10 LPT is 10000000000000000000 then shouldn't the program be able to read 10 and then multiply it the 18th power to accurately be 10000000000000000000? (10*10^18) 

Below is an example of What I have in my wallet + what I have bonded. Without seeing this number provided by livepeer_cli I'd have no idea that It was 30+18 other digits.
![image](https://user-images.githubusercontent.com/15055337/149665165-42dd4bd5-2064-47b4-9d97-2bb05831829c.png)
however, shown below, a simpler input is easily converted to the long format that is currently required and could be simplified further for all users/orchestrators. 
![image](https://user-images.githubusercontent.com/15055337/149665232-55ce0246-d4f7-4456-86d0-0c4ef794a76b.png)

**Additional context**
This seems like it may be a low hanging fruit to accomplish, maybe theres a reason that this isn't this way who knows but it seems like a change that makes sense to do.

**Comment by hthillman** [comment] 2022-01-18 15:21
@yondonfu do you have any insight on why we do it this way? Granularity is the only reason i can think of

**Comment by hthillman** [comment] 2022-01-20 23:47
closing as dupe of https://github.com/livepeer/go-livepeer/issues/1835. added #1835 to backlog for prioritization

**Closed as completed by hthillman** 2022-01-20 23:47 UTC
Labels: area: cli, need: more info
