### ISSUE TITLE
O is not receiving test streams since 24hrs

### ISSUE THREAD

**Issue by ChuckChain** [livepeer/go-livepeer#2279] opened 2022-02-19 13:55 UTC
**Describe the bug**
Over the last 24 hours, our O (0x9D5611bf0DAdddb4441A709141d9229d7F6b3e47) is no longer receiving test streams from any of the test ingest regions.

**To Reproduce**
Please see our test results:
https://interptr-latest-test-streams.vercel.app/?address=0x9D5611bf0DAdddb4441A709141d9229d7F6b3e47 

**Expected behavior**
The O should receive test streams for all test ingest regions.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
The O migrated to Arbitrum on 15-02-2022 and had been receiving test streams and performing similarly to how it was pre-migration for the first couple of rounds since migration (Total Score of around 9.6-9.7 / 10 in the Global region both pre- and post-migration). The bug only appeared in the last 24 hours.

The bug does not appear to have affected the amount of transcoding work the O currently receives.

This bug is likely related to #2270 - but since it didn't start immediately post-migration to Arbitrum, I'm creating this issue in case it's unrelated (please feel free to merge if necessary).

**Comment by JJassonn69** [comment] 2022-02-20 07:43
Is the issue still persistent after updating the serviceURL?

**Comment by ChuckChain** [comment] 2022-02-20 15:01
> Is the issue still persistent after updating the serviceURL?

Yes.

The metrics show that it keeps returning the `NoOrchestrators` error:
https://leaderboard-serverless.vercel.app/api/raw_stats?orchestrator=0x9D5611bf0DAdddb4441A709141d9229d7F6b3e47

This would suggest the test B is unable to find my O during the discovery phase. Even though it was properly registered already, I tried re-registering the on-chain serviceURI with two transactions - (1) from _domain:8935_ to _ip:8935_ and (2) back to _domain:8935_ - but the issue is still present. The O is using a Route53 setup, but it received test streams on L1 and for the first few rounds on L2; and I know other Os using Route53 are currently able to get test streams according to the performance leaderboard.

**Comment by JJassonn69** [comment] 2022-02-20 15:31
If you can share the domain, I would be able to check if its routing properly.

**Comment by ChuckChain** [comment] 2022-02-20 15:46
Thanks, I already checked, it is. The O is getting the same amount of work from all regions - real/normal streams are received correctly. The problem is really only with the test streams.

**Comment by ChuckChain** [comment] 2022-02-21 18:43
Update: the two most recent stream tests (LON and MDW) were received and processed correctly by the O.

**Comment by hthillman** [comment] 2022-02-22 21:16
closing b/c the issue is likely a problem with the test stream infrastructure and not a bug in the node software - we're looking into that separately. if it turns out to be an issue in the node software, we'll reopen

**Closed as completed by hthillman** 2022-02-22 21:16 UTC

**Comment by yondonfu** [comment] 2022-02-23 02:33
@ChuckChain Looks like you've been successfully receiving test streams across all regions recently. Please follow up if this is not the case or you've continued observed problems receiving test streams.

**Comment by ChuckChain** [comment] 2022-02-23 03:14
@yondonfu Yes, everything looks to be back to normal. Thanks.
