### ISSUE TITLE
Return error to B from O before panic due to unrecoverable LPMS error

### ISSUE THREAD

**Issue by yondonfu** [livepeer/go-livepeer#2070] opened 2021-10-25 17:31 UTC
Repost from https://github.com/livepeer/go-livepeer/pull/2057#issuecomment-950984324

> I don't think the HTTP conn will be closed cleanly if the O/T panics in the middle of a transcode.

> I think the B will wait for a timeout and then switch to a different O/T.

> It would be preferable if the O/T could return an error immediately to B so B can switch before the O/T panics so that B doesn't have to wait for a timeout. Maybe panic recovery as described in this post could help here? The O/T could recover from the panic, return the error and then trigger another panic to crash. An alternative would be for go-livepeer to check for the unrecoverable LPMS error introduced in https://github.com/livepeer/lpms/pull/267/files and trigger the panic only in go-livepeer instead of triggering it in LPMS.

**Comment by yondonfu** [comment] 2021-11-05 19:30
Relevant areas of the codebase:

The transcoding call for a combined OT happens here:

https://github.com/livepeer/go-livepeer/blob/d3a869665318cc69126427260e7ac0b4f106bf85/core/orchestrator.go#L557

Note that we use a single `Transcoder` interface that can be implemented by `RemoteTranscoderManager` when running as a standalone O and that can be implemented by `LoadBalancingTranscoder` (which uses `NvidiaTranscoder` under the hood for each individual GPU device available) or `LocalTranscoder`. When we run a combined OT with GPU access we default to using `LoadBalancingTranscoder` as the implementation for the `Transcoder` interface - see [here](https://github.com/livepeer/go-livepeer/blob/d3a869665318cc69126427260e7ac0b4f106bf85/cmd/livepeer/livepeer.go#L296).

[transcodeSeg()](https://github.com/livepeer/go-livepeer/blob/d3a869665318cc69126427260e7ac0b4f106bf85/core/orchestrator.go#L498) returns `TranscodeResult` which can include an error. This error is propagated back to `sendToTranscodeLoop` and returned [here](https://github.com/livepeer/go-livepeer/blob/d3a869665318cc69126427260e7ac0b4f106bf85/core/orchestrator.go#L495). This error is then passed from [TranscodeSeg()](https://github.com/livepeer/go-livepeer/blob/d3a869665318cc69126427260e7ac0b4f106bf85/core/orchestrator.go#L98) to [ServeSegment()](https://github.com/livepeer/go-livepeer/blob/d3a869665318cc69126427260e7ac0b4f106bf85/server/segment_rpc.go#L171). Then, the error can be returned to the B over the network.

**Comment by leszko** [comment] 2021-11-08 13:50
I think that B does not wait for any timeout when O crashes. At least I wasn't able to reproduce such a scenario. Here is how the communication looks like.

1. B submits a segment to O ([SubmitSegment()](https://github.com/livepeer/go-livepeer/blob/a856c10c2deedc512862f3af207ca33922f2ea26/server/segment_rpc.go#L382))
2. O responds with HTTP_OK 200 ([ServeSegment()](https://github.com/livepeer/go-livepeer/blob/a856c10c2deedc512862f3af207ca33922f2ea26/server/segment_rpc.go#L160))
3. B receives the response and then synchronously blocks on waiting for the transcoded data ([via ioutil.ReadAll()](https://github.com/livepeer/go-livepeer/blob/a856c10c2deedc512862f3af207ca33922f2ea26/server/segment_rpc.go#L499))
4. O is transcoding the data and pushing until done (EOF)
5. B unblocks after receiving all the data ended with EOF

Now, O can fail in two ways:
1. Panicking: then the stream of transcoded data is automatically closed and [B does not wait for any timeout, it suddenly prints `Unable to read response body for segment nonce`](https://github.com/livepeer/go-livepeer/blob/a856c10c2deedc512862f3af207ca33922f2ea26/server/segment_rpc.go#L503)
1. Return an error: B [suddenly checks the transcoding error and prints the relevant message](https://github.com/livepeer/go-livepeer/blob/a856c10c2deedc512862f3af207ca33922f2ea26/server/segment_rpc.go#L524)

I think this a correct behavior. @yondonfu wdyt?

**Comment by leszko** [comment] 2021-11-08 15:12
Confirmed with @yondonfu that it's not an issue. Closing.

**Closed as completed by leszko** 2021-11-08 15:12 UTC
