### ISSUE TITLE
Logging system improvement proposal

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/go-livepeer#808] opened 2019-04-04 17:13 UTC
### Problem statement
Currently, go-client writes logs to `stderr`, and from there we're routing them
(using built-in docker capability) to Google's logging aggragation solution
(Stackdriver). Logs flows into Stackdriver as raw strings - and that leads to
the information about individual log entry being lost. Though internally in application
each log entry has `level` property, and Stackdriver has same property for log entry,
but that information gets lost because log entry gets converted to the raw string
during the process. So we're loosing ability filter logs by level on Stackdriver
(same applies to any other aggregation system to which we will export logs that way).
Plus we can't export any structured information from log in machine parseable way -
for example, Grafana with Loki promises that in the future it will be able to 
plot graphs based on info in logs that looks like this: `duration=1s`.
Right now, with `glog` we can't export such structured information explicitly, only
by constracting strgins manually - that doesn't allow to switch output format, if needed,
say to json.

## Possibly solution
We should have option to export logs dirctly from application to log aggregator of choice - this would prevent loosing information in process. Plus we should switch from using `glog` to another logging library which support structured logging. Possible candidates are [zerolog](https://github.com/rs/zerolog) and [zap](https://github.com/uber-go/zap). Currently used `glog`, besides not being able to do structured logging, has another very big flaw - it doesn't allow plugin loggers - it only outputs to files or to `stderr`, without any option to direct logs anywhere else. So only possibility to redirect logs from `glog` is to use `os.Pipe` (which I've did in Loki integration PR) - which creates real file handles and pipes data through operation system - which is not very good solution, obviously. Plus I'm parsing raw strings to get some structured information back - which is not helping performance, too.

So proposal is to switch `glog` to `zap` in our code, and add optional log exporters (for Loki at least). Libraries we use (go-ethereum mainly) will still be using `glog`, so redirection through `stderr` will still be needed, but at least our code will be outputting structured logs.

**Comment by j0sh** [comment] 2019-04-04 20:16
> Though internally in application
each log entry has level property, and Stackdriver has same property for log entry,
but that information gets lost because log entry gets converted to the raw string
during the process. 

Can you elaborate on this? If I'm understanding correctly, this is the root of the issue with logging. Perhaps we can try and solve this directly.

**Comment by darkdarkdragon** [comment] 2019-04-04 23:42
@j0sh 
Each log entry inside application has this properties: timestamp. log level, source location (file/line) and message itself. Both Stackdriver and Loki able to save this as meta-data for log entry, and allow to easily filter on these fields. But all this gets lost when logs go through `stderr`.

**Comment by j0sh** [comment] 2019-04-05 00:23
>  But all this gets lost when logs go through stderr

I'm not exactly clear on what the issue is. All the properties you mentioned are already in the stderr output. Is the problem that Stackdriver/Loki aren't parsing the first parts of each log line? Can we set up a log parser for those tools [1]?

Or we could adjust the glog formatting scheme to match whatever the standard is. Can we get some more mileage out of tightening our existing logging? For example, using key=value entries in more places (eg, `mid=abc duration=10s`) and so forth?

[1] Are we using the Stackdriver log collector? Does this help? https://cloud.google.com/logging/docs/agent/configuration

**Comment by darkdarkdragon** [comment] 2019-04-05 17:28
> Stackdriver/Loki aren't parsing the first parts of each log line

Nobody parses logs. Docker just takes output from `stderr` and though it's [plugin](https://docs.docker.com/config/containers/logging/gcplogs/) sends it line-by-line to Google, without doing any parsing. We can write out logging driver for docker that will do parsing, but what if we move somewhere from docker? 
And in this config, there is no easy way to put any log parser in between our process and Google Cloud. We can create some configuration - but this will require writing logs to special shared volume and running separate docker container with mentioned Stackdriver log collector accessing that shared volume. Not the kind of configuration I want to support.

> Or we could adjust the glog formatting scheme to match whatever the standard is. 

No standard.

>  For example, using key=value entries in more places (eg, mid=abc duration=10s) and so forth?

This same as our reasoning about OpenCensus vs native Prometheus driver - while we certainly can force ourselves to format log messages in certain way, but what if someone will want to output to different format (JSON for example)? With structured logging lib it's matter of switching encoder, but if we format messages manually then there is no way to do it.

BTW, docker don't parse logs for performance reasons - and I'm totally agree with them - encoding information into text strings and decoding it back couple of nanoseconds later seems like unnecessary contribution into global warming 😄

**Comment by j0sh** [comment] 2019-04-05 23:39
> Nobody parses logs.

What do you mean by this? Parsing is very common thing for log collectors. Logstash, mtail, fluentd, etc all do that. Stackdriver's logger is itself based on fluentd and seems to use a similar configuration format. See the link that I shared earlier.

>> Or we could adjust the glog formatting scheme to match whatever the standard is.

> No standard.

Not even syslog? That should be supported by basically all log collectors.

> Docker just takes output from stderr and though it's plugin sends it line-by-line to Google, without doing any parsing. We can write out logging driver for docker that will do parsing, but what if we move somewhere from docker?

We don't necessarily have to run a collector for each Docker instance, but it could be on the VM (isn't this what stackdriver does?) or somewhere else central.

Don't get me wrong, I'm not necessarily against structured logging. But this is a pretty big change for us, and I want to make sure that it's giving us a clear benefit. So I want to fully understand the issue: is the issue getting Stackdriver / Loki to recognize basic log metadata? Will we be using the structured logging aspect for anything other than basic metadata?

Replacing all our existing logging feels rushed without fully considering non-invasive alternatives to solving this problem. I'm also reluctant to enlarge the goclient with flavor-of-the-month tools (eg, Loki integration) because that is something we have to ship and support for everyone even though we're building this for ourselves, and it does introduce a maintenance burden (as you mentioned the API is not stable). If the log-metadata issue is something we can selectively improve outside the goclient for our own purposes, then I'd really prefer that option.

**Comment by darkdarkdragon** [comment] 2019-04-18 17:35
> What do you mean by this?

In our setup.

> Stackdriver's logger 

We're not using it.

> We don't necessarily have to run a collector for each Docker instance, but it could be on the VM (isn't this what stackdriver does?) or somewhere else central.

This breaks Docker's abstraction. I can install fluentd on local machine, point docker to it, and point fluentd to Loki running inside docker container on other machine. But this wouldn't work in local docker-compose based setup.

> So I want to fully understand the issue

Main issue right now is that `glog` doesn't allow to plug in output drivers to output logs anywhere else than to `stderr`. 

> Replacing all our existing logging feels rushed

That's why my current solution is to redirect `glog` output from inside go-client without completely replacing `glog`.

>  and it does introduce a maintenance burden

Yes, but I think here potential gain outweighs potential problems.

**Comment by ericxtang** [comment] 2020-01-29 19:49
To summarize the conversation from the Jan 2020 eng retro, we should:
* Include ManifestID in all relevant log lines
* Document our log format, and enforce the same format across repos (in Github repos)
* Create custom function for logging

**Comment by darkdarkdragon** [comment] 2020-01-29 20:14
> Create custom function for logging

I really don't understand what this means.

**Comment by j0sh** [comment] 2020-01-29 21:36
For what it's worth, the original proposal was around migrating to a different library for structured logging. Should we create separate ticket(s) to track these other items?

 @darkdarkdragon are you still interested in pursing structured logging as in this ticket? If not, should we close this?

**Comment by darkdarkdragon** [comment] 2020-01-30 01:56
@j0sh 
I'm trying to make clear what `Create custom function for logging` means.
From what I've understood from our meeting, this `custom function` should do exactly what libraries for structured logging doing.

**Closed as completed** 2022-01-25 21:42 UTC
