### ISSUE TITLE
Fix flaky TranscoderActivated test

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/go-livepeer#1408] opened 2020-02-29 19:35 UTC
**Describe the bug**

This test sometimes fails: 

```
--- FAIL: TestOrchWatcher_HandleLog_TranscoderActivated (0.01s)
    orchestratorwatcher_test.go:79:
        	Error Trace:	orchestratorwatcher_test.go:79
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestOrchWatcher_HandleLog_TranscoderActivated
```

**Comment by yondonfu** [comment] 2020-03-02 14:31
Looks like this is a duplicate of #1370 so I'm going to close this issue and we can track this bug in #1370.

**Closed as completed by yondonfu** 2020-03-02 14:31 UTC
